# Generated by Django 6.0.7 on 2026-07-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAccueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accueil/slide/')),
                ('legende', models.CharField(blank=True, help_text="Texte optionnel affiché sous l'image (ex : 'Un plombier chez un client à Cocody').", max_length=150, null=True)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans le diaporama (0 = premier).")),
                ('est_active', models.BooleanField(default=True, help_text="Décochez pour retirer l'image du diaporama sans la supprimer.")),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Image du diaporama d'accueil",
                'verbose_name_plural': "Images du diaporama d'accueil",
                'ordering': ['ordre', '-date_ajout'],
            },
        ),
    ]
