# Generated by Django 6.0.7 on 2026-07-09 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropositionDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_propose', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True, help_text='Détail du devis : délai, matériel inclus, etc.', null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proposition de devis',
                'verbose_name_plural': 'Propositions de devis',
                'ordering': ['montant_propose'],
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('mission_directe', 'Mission directe'), ('demande_devis', 'Demande de devis')], default='mission_directe', max_length=20)),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('zone_geographique', models.CharField(max_length=150)),
                ('budget_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_acceptation', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('artisan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='artisans.artisanprofile')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='categories.categorie')),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
