# Generated by Django 6.0.7 on 2026-07-09 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0002_initial'),
        ('demandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propositiondevis',
            name='artisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis_envoyes', to='artisans.artisanprofile'),
        ),
        migrations.AddField(
            model_name='propositiondevis',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions_devis', to='demandes.demande'),
        ),
        migrations.AlterUniqueTogether(
            name='propositiondevis',
            unique_together={('demande', 'artisan')},
        ),
    ]
