# Generated by Django 6.0.7 on 2026-07-09 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoRealisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='realisations/')),
                ('legende', models.CharField(blank=True, max_length=150, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtisanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('competences', models.TextField(blank=True, help_text='Liste de compétences séparées par des virgules.', null=True)),
                ('annees_experience', models.PositiveIntegerField(default=0)),
                ('zone_geographique', models.CharField(help_text="Commune / quartier principal d'intervention.", max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('statut_validation', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=15)),
                ('piece_identite', models.FileField(blank=True, null=True, upload_to='verifications/identite/')),
                ('justificatif_metier', models.FileField(blank=True, null=True, upload_to='verifications/metier/')),
                ('note_admin', models.TextField(blank=True, help_text="Commentaire de l'administrateur lors de la validation/rejet.", null=True)),
                ('badge_confiance', models.BooleanField(default=False)),
                ('est_premium', models.BooleanField(default=False)),
                ('premium_jusqu_au', models.DateTimeField(blank=True, null=True)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('nombre_avis', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('categorie_principale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artisans_principaux', to='categories.categorie')),
                ('categories_secondaires', models.ManyToManyField(blank=True, related_name='artisans_secondaires', to='categories.categorie')),
            ],
            options={
                'verbose_name': 'Profil artisan',
                'verbose_name_plural': 'Profils artisans',
                'ordering': ['-note_moyenne', '-date_creation'],
            },
        ),
    ]
