# Generated by Django 6.0.7 on 2026-07-09 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_artisan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photorealisation',
            name='artisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='artisans.artisanprofile'),
        ),
    ]
