# Generated by Django 6.0.7 on 2026-07-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icone', models.CharField(blank=True, help_text="Nom/clé d'icône utilisée par le frontend (ex: 'plomberie').", max_length=50, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie de métier',
                'verbose_name_plural': 'Catégories de métiers',
                'ordering': ['nom'],
            },
        ),
    ]
